############################################ DEFAULT
# ?? ????? ???? ??? ??? ??? ????.
spring:
  profiles:
    active: local # default profile? ????.

---
############################################ LOCAL

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

    logging:
      level:
        org.hibernate.SQL: debug
        # org.hibernate.type: trace #??? ?? 2.x, hibernate5
        org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6

  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration/{vendor},classpath:db/seed/local # when you want to give test seed, add location test seed too

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

# jwt.secret? ??? ???? base64? ???? ?? ???????. ?? ?? ?? ??????. ??? exception? ????? ??? ?? ?????.
jwt:
  header: Authorization
  secret: aGVsbG8gd29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2EK # fill in base64 [command: echo {plain_text} | base64]
  refresh-token-secret: d29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2FkCg== # it must be different from the access key secret
  access-token-validity-in-seconds: 600 # 10 min
  refresh-token-validity-in-seconds: 86400 # 24 hour # ??? ?? ?? ? 1?